import re

with open('assets/index-WKGCUSBO.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Fix remaining product 3 (kit-deleite) description parts that weren't replaced
content = content.replace(
    "BODY SPLASH\nO Body Splash Cuide-Se Bem Deleite prolonga a sensação de frescor pós-banho com sua fragrância leve e suave.\nA fragrância gourmand traz na saída anis fresco estrelado, aliado ao coração com frésia, flor de caramelo, orquídea, marshmallow de ouro, chantilly e vanilla. Por fim, a base é composta por benjoim, sândalo, ambrette, creme de baunilha, cedro cremoso e fluffy musk.\n\nLOÇÃO CORPORAL\nA Loção Desodorante Hidratante Corporal Cuide-se Bem Deleite confere até 48 horas de hidratação e perfumação do jeito que a gente gosta. Sua textura é absorvida rapidamente pela pele e também desodoriza o corpo.\n\nCREME PARA MÃOS\nCom a mesma perfumação da linha, o Creme para Mãos Hidratante Desodorante Cuide-se Bem Deleite hidrata intensamente mãos e cotovelos por até 30 horas.\n\nCAIXA PARA PRESENTE\nA sofisticada ânfora, símbolo de Wepink, centraliza esta embalagem especial.\nDimensões: 14,5 x 5 x 18,5 cm",
    "VF AQUA DEO COLÔNIA 100ML\nFragrância aquática e refrescante, com notas cítricas, marinhas e um toque de musk. Ideal para quem busca frescor e leveza no dia a dia.\n\n5 BODY SPLASHES EXCLUSIVOS\nO kit acompanha os 5 body splashes mais desejados da Wepink: Liberté, Body Splash clássico, Obsessed, RED e Infinity. Fragrâncias versáteis para todos os momentos.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free, com perfumação de longa duração."
)

# Fix remaining product 4 (kit-pessegura) description
content = content.replace(
    "CREME HIDRATANTE DESLIZANTE\nO Creme Hidratante Deslizante Para Lâmina Cuide-se Bem Doçura na Pessegura facilita o deslizar da lâmina durante a depilação, seja no banho ou na pele seca. Sua textura semi transparente proporciona sensação calmante na pós-depilação.\n\nCREME HIDRATANTE DEPILATÓRIO CORPORAL\nO Creme Hidratante Depilatório Corporal Cuide-se Bem Doçura na Pessegura remove os pelos de forma prática, indolor e eficiente em até 10 minutos, garantindo pele lisinha por até 5 dias.\n\nSÉRUM UNIFORMIZADOR CORPORAL\nO Sérum Uniformizador Corporal Cuide-se Bem Doçura na Pessegura hidrata e ajuda a uniformizar o tom da pele, prevenindo e minimizando pelos encravados, ideal para uso diário em áreas específicas.\n\nCREME ESFOLIANTE\nO Creme Esfoliante Intenso Cuide-se Bem Doçura na Pessegura promove esfoliação intensa sem ressecar a pele, removendo células mortas e deixando a pele renovada e macia. Recomendado para uso até três vezes por semana.\n\nBODY SPLASH\nO Body Splash Desodorante Colônia Cuide-se Bem Doçura na Pessegura traz a fragrância doce de cocada com pêssego, proporcionando frescor e perfumação ao longo do dia.\n\nLOÇÃO CORPORAL\nA Loção Desodorante Hidratante Cuide-se Bem Doçura na Pessegura possui textura cremosa, hidrata profundamente e perfuma a pele. Com Óleo de Coco e 97% de ingredientes de origem natural, sua fórmula é também biodegradável.\n\nSABONETE EM BARRA\nOs Sabonetes em Barra Cuide-se Bem Doçura na Pessegura oferecem espuma cremosa que limpa delicadamente sem ressecar, deixando a pele perfumada e aveludada. O kit contém 4 unidades e 97% de ingredientes naturais.\n\nCuide-se Bem: sua pele merece este carinho!",
    "HEAVEN DEO COLÔNIA 100ML\nFragrância floral celestial com notas de jasmim, lírio e um toque de musk branco. Sofisticada e envolvente, perfeita para mulheres que buscam elegância e delicadeza.\n\nBODY SPLASH LIBERTÉ DEO COLÔNIA 200ML\nFloral fresca e sofisticada, com notas de flores brancas e um toque cítrico.\n\nBODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais suaves e envolventes.\n\nOBSESSED DEO COLÔNIA 200ML\nIntensa e marcante, com notas de amora, cereja e maçã.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas, avelã e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix remaining product 5 (combo-chocolate) description
content = content.replace(
    "SABONETE EM BARRA\nO Sabonete em Barra Corporal Cuide-se Bem Deleite Especial oferece uma espuma cremosa e fragrância deliciosa inspirada no chocolate*, limpando sem ressecar e deixando a pele macia e aveludada.\n\nCREME ESFOLIANTE\nO Creme Esfoliante Cuide-se Bem Deleite Chocolatudo entrega renovação da pele com textura cremosa e fragrância inspirada no cheirinho de chocolate*. Esfolia suavemente, deixando a pele hidratada, macia e perfumada.\n\nNenhum produto da Wepink é testado em animais, ou seja, este item possui selo Cruelty Free.",
    "BODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais suaves e envolventes.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix remaining product 5 features
content = content.replace(
    '"01 Egeo Choc High Desodorante Colônia","01 Suflê Hidratante Desodorante Corporal Egeo Choc High","01 Sabonete em Barra Cuide-se Bem Deleite Especial","01 Creme Esfoliante Cuide-se Bem Deleite Chocolatudo"',
    '"01 Obsessed Deo Colônia 100ml","01 Body Splash Liberté 200ml","01 Body Splash Deo Colônia 200ml","01 RED Deo Colônia 200ml","01 Infinity Body Splash 200ml"'
)

# Fix remaining product 9 (kit-chocolatudo) description parts
content = content.replace(
    "BODY SPLASH\nO Body Splash Desodorante Colônia Cuide-se Bem Deleite Chocolatudo prolonga a sensação de frescor pós-banho com fragrância deliciosa e refrescante, ideal para levar na bolsa.\n\nCREME ESFOLIANTE\nO Creme Esfoliante Cuide-se Bem Deleite Chocolatudo renova a pele sem agredir, com textura cremosa e cheirinho de chocolate, deixando a pele macia, hidratada e perfumada.\n\nSABONETE EM BARRA\nO Sabonete em Barra Corporal Cuide-se Bem Deleite Especial oferece espuma cremosa e fragrância deliciosa inspirada no chocolate. Limpa a pele suavemente, deixando-a macia e aveludada.\n\nGLOSS LABIAL MARROM\nO Gloss Labial Marrom Intense Deleite Chocolatudo entrega um toque de cor marrom com efeito super glossy. Fórmula hidratante, não pegajosa e com aroma irresistível de chocolate.\n\nGLOSS LABIAL ROSA\nO Gloss Labial Rosa Intense Deleite Chocolatudo proporciona um toque de cor rosa, brilho intenso, hidratação e cheirinho de chocolate.\n\nPALETA DE MAQUIAGEM MULTIFUNCIONAL\nA Paleta de Maquiagem Multifuncional Cuide-se Bem Chocolatudo traz 8 cores versáteis para criar looks incríveis para olhos e rosto. Com textura macia e aplicação fácil.\n\nLOÇÃO CORPORAL 200ML\nA versão viagem da Loção Desodorante Hidratante Corporal Cuide-se Bem Deleite Chocolatudo é perfeita para o dia a dia, mantendo a pele hidratada e perfumada onde você estiver.\n\n*Fragrância inspirada no cheirinho de chocolate.",
    "BODY SPLASH LIBERTÉ DEO COLÔNIA 200ML\nFloral fresca e sofisticada, com notas de flores brancas e um toque cítrico.\n\nBODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais suaves e envolventes.\n\nOBSESSED DEO COLÔNIA 200ML\nIntensa e marcante, com notas de amora, cereja e maçã.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas, avelã e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix remaining product 9 features
content = content.replace(
    '"01 Loção Desodorante Hidratante Corporal 400ml","01 Body Splash Desodorante Colônia","01 Creme Esfoliante","01 Sabonete em Barra Deleite Especial","01 Gloss Labial Marrom Intense","01 Gloss Labial Rosa Intense","01 Paleta de Maquiagem Multifuncional","01 Loção Desodorante Hidratante Corporal 200ml"',
    '"01 Fatal Black Deo Colônia 100ml","01 Body Splash Liberté 200ml","01 Body Splash Deo Colônia 200ml","01 Obsessed Deo Colônia 200ml","01 RED Deo Colônia 200ml","01 Infinity Body Splash 200ml"'
)

# Fix remaining product 1 (kit-nuvem-de-alegria) description - using actual newlines
content = content.replace(
    "BODY SPLASH DESODORANTE COLÔNIA CUIDE-SE BEM NUVEM DE ALEGRIA 200ML\nO Body Splash Desodorante Colônia Cuide-se Bem Nuvem de Alegria chegou para dar aquela levantada no seu astral!\nCom uma fragrância frutal cítrica que promove sensação de felicidade*, inspira ao seu redor uma verdadeira nuvem de alegria! Para todos os momentos do seu dia, é seu aliado no ritual de autocuidado, deixando a pele perfumada.\n\nLOÇÃO DESODORANTE CORPORAL ILUMINADORA CUIDE-SE BEM NUVEM DE ALEGRIA 150ML\nA Loção Desodorante Iluminadora Corporal Cuide-se Bem Nuvem de Alegria chegou para dar aquela levantada no seu astral! Hidratante com brilho para deixar sua pele iluminada, entrega uma fragrância frutal cítrica que promove sensação de felicidade.\n\nÓLEO HIDRATANTE CORPORAL CUIDE-SE BEM NUVEM DE ALEGRIA 110ML\nO Óleo Hidratante Corporal Cuide-se Bem Nuvem de Alegria chegou para dar aquela levantada no seu astral! O primeiro e único óleo corporal de Cuide-se Bem Wepink, entrega pele aveludada como nuvem.\n\nLOÇÃO HIDRATANTE DESODORANTE CORPORAL CUIDE-SE BEM NUVEM DE ALEGRIA 400ML\nA Loção Hidratante Desodorante Corporal Cuide-se Bem Nuvem de Alegria chegou para dar aquela levantada no seu astral! Com textura cremosa como nuvem, entrega uma fragrância frutal cítrica que promove sensação de felicidade.\n\nKIT SABONETES SORTIDOS CUIDE-SE BEM NUVEM DE ALEGRIA 4X80G\nO Kit Sabonetes Sortidos Cuide-se Bem Nuvem de Alegria chegou para dar aquela levantada no seu astral! Com uma fragrância frutal cítrica que promove sensação de felicidade.\n\nSABONETE LÍQUIDO CORPORAL CUIDE-SE BEM NUVEM DE ALEGRIA 150ML\nO Sabonete Líquido Corporal Cuide-se Bem Nuvem de Alegria chegou para dar aquela levantada no seu astral e brilho para um banho iluminado!\n\nNenhum produto Wepink é testado em animais, ou seja, este item possui selo Cruelty Free. Produto vegano.",
    "BLOQUINHO DA VIVIBORA VF BLOOM DEO COLÔNIA 100ML\nFragrância floral delicada e feminina, com notas de flores frescas, peônia e um toque de musk. Perfeita para quem ama suavidade e elegância no dia a dia.\n\nBODY SPLASH LIBERTÉ DEO COLÔNIA 200ML\nFloral fresca e sofisticada, com notas de flores brancas e um toque cítrico. Leveza e feminilidade.\n\nBODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais suaves e envolventes.\n\nOBSESSED DEO COLÔNIA 200ML\nIntensa e marcante, com notas de amora, cereja e maçã.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas, avelã e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix product 1 features
content = content.replace(
    '"01 Body Splash Desodorante Colônia 200ml","01 Loção Desodorante Corporal Iluminadora 150ml","01 Óleo Hidratante Corporal 110ml","01 Loção Hidratante Desodorante Corporal 400ml","04 Sabonetes Sortidos 80g cada","01 Sabonete Líquido Corporal 150ml"',
    '"01 Bloquinho da Vivibora VF Bloom Deo Colônia 100ml","01 Body Splash Liberté 200ml","01 Body Splash Deo Colônia 200ml","01 Obsessed Deo Colônia 200ml","01 RED Deo Colônia 200ml","01 Infinity Body Splash 200ml"'
)

# Fix remaining product 2 (kit-celebre-sua-forca) description
content = content.replace(
    "Amor de mãe é símbolo de força e persistência. O Kit Presente Dia das Mães Celebre Sua Força celebra esse amor que transborda, com dois itens de perfumação, hidratação e cuidado diário, embalados em uma caixa especial:\n\nDESODORANTE COLÔNIA\nCelebre Sua Força Feminino Desodorante Colônia traz uma fragrância floral, fresca e potente, para lembrar do quanto é importante celebrar o amor nas pequenas conquistas do dia a dia. Esse Floral Frutal carrega a potência das flores brancas e das frutas em uma perfumação que explode, cheia de frescor.\nFamília Olfativa: Floral Frutal.\n\nLOÇÃO CORPORAL\nA Loção Hidratante Desodorante Corporal Celebre Sua Força traz uma fórmula que absorve de forma rápida na pele, hidratando intensamente e desodorizando o corpo. O resultado é uma pele hidratada e macia.\n\nCAIXA PARA PRESENTE\nA Caixa de Presente Wepink vem com o tamanho ideal para acomodar os produtos com segurança. Sofisticada e minimalista, as flores estampam a embalagem em 3D, representando o amor abundante que se encaixa em toda a área do presente.\nDimensões: 14 x 5,4 x 18,6 cm\n\nMAIS PRESENTE\nVocê compra um presente, sua pessoa especial ganha dois! Como funciona? Dentro de cada kit tem uma tag com um QR Code que dá acesso ao site exclusivo. Neste site, a presenteada escolhe um presente extra e recebe um voucher para resgatá-lo.\n\nNo Dia das Mães 2025, surpreenda a sua pessoa especial com a Wepink!\n\nNenhum produto Wepink é testado em animais, ou seja, este item possui selo Cruelty Free.",
    "O Kit Merry Christmas Wepink é a edição especial de Natal que combina o perfume Merry Christmas com 5 body splashes exclusivos. Uma coleção festiva e encantadora:\n\nMERRY CHRISTMAS DEO COLÔNIA 100ML\nFragrância festiva e envolvente, com notas de frutas vermelhas, especiarias e baunilha. Perfeita para celebrar momentos especiais com elegância e alegria.\nFamília Olfativa: Frutal Especiado.\n\nBODY SPLASH LIBERTÉ DEO COLÔNIA 200ML\nFloral fresca e sofisticada, com notas de flores brancas e um toque cítrico.\n\nBODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais envolventes.\n\nOBSESSED DEO COLÔNIA 200ML\nIntensa e marcante, com notas de amora, cereja e maçã.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas, avelã e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix product 2 features
content = content.replace(
    '"01 Celebre Sua Força Feminino Desodorante Colônia 100ml","01 Loção Desodorante Hidratante Corporal 200ml"',
    '"01 Merry Christmas Deo Colônia 100ml","01 Body Splash Liberté 200ml","01 Body Splash Deo Colônia 200ml","01 Obsessed Deo Colônia 200ml","01 RED Deo Colônia 200ml","01 Infinity Body Splash 200ml"'
)

# Fix remaining product 6 (kit-liz-sublime) description
content = content.replace(
    "O Kit Liz Sublime é uma opção incrível para surpreender. O kit contém dois itens, de perfumaria e cuidados com o corpo, com a fragrância inconfundível de Liz, embalados em uma linda caixa especial. Confira os detalhes:\n\nDESODORANTE COLÔNIA\nO Liz Sublime Desodorante Colônia possui uma fragrância feminina que combina notas frutais com a base exclusiva de Laire Íris Nobre, assinatura de Liz. Ideal para mulheres sublimes que brilham todos os dias!\nFamília Olfativa: Amadeirado Frutal.\n\nLOÇÃO DESODORANTE HIDRATANTE CORPORAL\nA Loção Desodorante Hidratante Corporal Liz Sublime traz uma textura leve que hidrata e deixa a pele macia, com um toque seco e a mesma perfumação marcante do desodorante colônia.\n\nCAIXA PARA PRESENTE\nA Caixa de Presente Wepink possui tamanho ideal para acomodar os produtos com segurança. Com design sofisticado e flores estampadas em 3D, ela representa o amor abundante de um presente especial.\nDimensões: 21 x 21 x 7,5 cm.\n\nMAIS PRESENTE\nVocê compra um presente e sua pessoa especial ganha dois! Dentro de cada kit, uma tag com QR Code dá acesso a um site exclusivo para escolher um presente extra.\n\nSurpreenda quem você ama com a Wepink!\n\nNenhum produto Wepink é testado em animais, ou seja, este item possui selo Cruelty Free.",
    "O Kit Red Mirage Wepink traz o sedutor perfume Red Mirage 100ml junto com 5 body splashes exclusivos. Uma coleção para mulheres que amam fragrâncias envolventes:\n\nRED MIRAGE DEO COLÔNIA 100ML\nFragrância sedutora e misteriosa, com notas de frutas vermelhas escuras, especiarias e um toque amadeirado. Ideal para mulheres que amam fragrâncias marcantes e sensuais!\nFamília Olfativa: Frutal Amadeirado.\n\nBODY SPLASH LIBERTÉ DEO COLÔNIA 200ML\nFloral fresca e sofisticada, com notas de flores brancas e um toque cítrico.\n\nBODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais envolventes.\n\nOBSESSED DEO COLÔNIA 200ML\nIntensa e marcante, com notas de amora, cereja e maçã.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas, avelã e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix product 6 features
content = content.replace(
    '"01 Liz Sublime Desodorante Colônia 100ml","01 Loção Desodorante Hidratante Corporal Liz Sublime 100ml","01 Caixa de Presente Wepink"',
    '"01 Red Mirage Deo Colônia 100ml","01 Body Splash Liberté 200ml","01 Body Splash Deo Colônia 200ml","01 Obsessed Deo Colônia 200ml","01 RED Deo Colônia 200ml","01 Infinity Body Splash 200ml"'
)

# Fix remaining product 7 (kit-lily) description
content = content.replace(
    "O Kit Lily é a escolha perfeita para surpreender com elegância, carinho e sofisticação. Ele traz dois itens clássicos embalados em uma linda caixa especial. Confira:\n\nEAU DE PARFUM\nO Lily Eau De Parfum combina a delicadeza de notas florais com a intensidade das madeiras, resultando em uma fragrância feminina sofisticada. Sua assinatura olfativa é marcada pelo exclusivo óleo essencial da flor de Lírio, obtido pelo raro processo de Enfleurage.\nFamília Olfativa: Floral Bouquet\n\nCREME HIDRATANTE DESODORANTE ACETINADO\nO Creme Acetinado Hidratante Desodorante Corporal Lily entrega a fragrância icônica de Lily em uma textura aveludada. Sua fórmula, enriquecida com Manteiga de Karité e Vitamina E, proporciona hidratação intensa por até 48 horas e protege a pele com rápida absorção.\n\nCAIXA PARA PRESENTE\nA Caixa de Presente Wepink possui tamanho ideal para acomodar os produtos com segurança. Com design sofisticado e flores em relevo 3D, transmite amor e cuidado em cada detalhe. Feita em material rígido, pode ser reutilizada como porta-objetos.\nDimensões: 21 x 21 x 10,5 cm\n\nMAIS PRESENTE\nVocê compra um presente e sua pessoa especial ganha dois! Dentro de cada kit há um QR Code exclusivo que permite escolher um presente extra e resgatar um voucher especial.\n\nSurpreenda quem você ama com a Wepink!\n\nNenhum produto Wepink é testado em animais, ou seja, este item possui selo Cruelty Free.",
    "O Kit Queen Pink Wepink traz o elegante perfume Queen Pink 100ml junto com 5 body splashes exclusivos. Para mulheres que exalam sofisticação e feminilidade:\n\nQUEEN PINK DEO COLÔNIA 100ML\nFragrância floral sofisticada com notas de rosa, peônia e jasmim, combinadas com um toque de musk e sândalo. Feminina e elegante, perfeita para mulheres que buscam uma fragrância atemporal.\nFamília Olfativa: Floral Sofisticado\n\nBODY SPLASH LIBERTÉ DEO COLÔNIA 200ML\nFloral fresca e sofisticada, com notas de flores brancas e um toque cítrico.\n\nBODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais envolventes.\n\nOBSESSED DEO COLÔNIA 200ML\nIntensa e marcante, com notas de amora, cereja e maçã.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas, avelã e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix product 7 features
content = content.replace(
    '"01 Lily Eau De Parfum 75ml","01 Creme Acetinado Hidratante Desodorante Corporal Lily 250g"',
    '"01 Queen Pink Deo Colônia 100ml","01 Body Splash Liberté 200ml","01 Body Splash Deo Colônia 200ml","01 Obsessed Deo Colônia 200ml","01 RED Deo Colônia 200ml","01 Infinity Body Splash 200ml"'
)

# Fix remaining product 8 (kit-floratta-red) description
content = content.replace(
    "O Kit Floratta Red é inspirado na delicadeza da Flor da Maçã de Vermont, trazendo a clássica fragrância da linha, além de cuidar da pele com hidratação e perfumação. São três itens da linha e um nécessaire exclusivo embalados em uma caixa especial. Confira:\n\nDESODORANTE COLÔNIA\nO Floratta Red Desodorante Colônia combina a delicadeza da flor da maçã com a doçura da fruta, trazendo uma fragrância floriental frutal envolvente. Suas notas se abrem com frutas vermelhas, laranja e maçã, evoluem para flor de laranjeira, tuberosa, violeta, flor de lótus e flor do beijo, e finalizam com chocolate amargo, musk, sândalo, cedro e âmbar.\nFamília Olfativa: Floriental Frutal\n\nÓLEO PERFUMADO\nO Óleo Perfumado Desodorante Corporal Floratta Red proporciona uma pele perfumada e uma experiência deliciosa na hora do banho, trazendo a fragrância envolvente da linha.\n\nCREME HIDRATANTE DESODORANTE CORPORAL\nO Creme Hidratante Desodorante Corporal Floratta Red hidrata intensamente por até 48 horas e perfuma a pele com toque aveludado, perfeito para quem ama a fragrância floral.\n\nNÉCESSAIRE BRANCO\nO Nécessaire Branco Off White Wepink é compacto, elegante e ideal para levar itens essenciais na bolsa ou mochila, complementando o presente com charme e praticidade.\nDimensões: 23,4 x 12 x 14 cm\n\nCAIXA PARA PRESENTE\nA Caixa de Presente Wepink possui tamanho ideal para acomodar os produtos com segurança. Com design sofisticado e flores estampadas em 3D, é feita em material rígido, ideal para ser reaproveitada como porta-objetos.\nDimensões: 30 x 21 x 8,3 cm\n\nMAIS PRESENTE\nVocê compra um presente e sua pessoa especial ganha dois! Cada kit contém um QR Code exclusivo que permite escolher um presente extra para resgate.\n\nSurpreenda a sua pessoa especial com a Wepink!\n\nNenhum produto Wepink é testado em animais, ou seja, este item possui selo Cruelty Free.",
    "O Kit The Sunny Wepink traz o radiante perfume The Sunny 75ml junto com 5 body splashes exclusivos. Uma coleção vibrante e ensolarada:\n\nTHE SUNNY DEO COLÔNIA 75ML\nFragrância solar e vibrante, com notas cítricas de bergamota e laranja, combinadas com flores tropicais e um toque de vanilla. Perfeita para mulheres que irradiam energia positiva.\nFamília Olfativa: Cítrico Floral\n\nBODY SPLASH LIBERTÉ DEO COLÔNIA 200ML\nFloral fresca e sofisticada, com notas de flores brancas e um toque cítrico.\n\nBODY SPLASH DEO COLÔNIA 200ML\nA fragrância clássica da Wepink. Notas florais e frutais envolventes.\n\nOBSESSED DEO COLÔNIA 200ML\nIntensa e marcante, com notas de amora, cereja e maçã.\n\nRED DEO COLÔNIA 200ML\nVibrante e apaixonante, com notas de frutas vermelhas, avelã e cacau.\n\nINFINITY BODY SPLASH DEO COLÔNIA 200ML\nSofisticada e duradoura, com notas florais e amadeiradas.\n\nTodos os produtos Wepink possuem fórmula vegana e cruelty-free."
)

# Fix product 8 features
content = content.replace(
    '"01 Floratta Red Desodorante Colônia 75ml","01 Creme Hidratante Desodorante Corporal Floratta Red 200ml","01 Óleo Perfumado Desodorante Corporal Floratta Red 150ml","01 Nécessaire Branco Off White Wepink"',
    '"01 The Sunny Deo Colônia 75ml","01 Body Splash Liberté 200ml","01 Body Splash Deo Colônia 200ml","01 Obsessed Deo Colônia 200ml","01 RED Deo Colônia 200ml","01 Infinity Body Splash 200ml"'
)

# Fix remaining product 9 (kit-chocolatudo) description
content = content.replace(
    "O Kit Celebrate Life te convida a mergulhar em doces momentos de autocuidado! Com produtos das linhas Cuide-se Bem e Intense, este combo proporciona uma rotina completa com o cheirinho irresistível de chocolate*. Confira os detalhes:\n\nLOÇÃO CORPORAL 400ML\nA Loção Desodorante Hidratante Corporal Cuide-se Bem Deleite Chocolatudo entrega hidratação intensa, textura cremosa e fragrância inspirada no chocolate. Deixa a pele macia, perfumada e protegida por até 48 horas.",
    "O Kit Fatal Black Wepink traz o intenso perfume Fatal Black 100ml junto com 5 body splashes exclusivos. Para mulheres que amam fragrâncias poderosas e marcantes:\n\nFATAL BLACK DEO COLÔNIA 100ML\nFragrância intensa e poderosa, com notas de pimenta preta, couro e um toque de vanilla escura. Sensual e misteriosa."
)

# Also clean up the footer text about Netflix
content = content.replace('Cuide-se Bem Netflix, Intense Netflix e Egeo', 'Wepink Netflix e edições especiais')

with open('assets/index-WKGCUSBO.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("Fix aplicado com sucesso!")
